---
title: "Data Telephone: A Game for Teaching Accessibility & Visual Literacy "
subtitle: "Presentation at Posters and Beyond Session of Electronic Conference on Teaching Statistics (eCOTS) 2026 "
authors: "Evan Fryer and Mine Doğucu"
title-block-banner: true
format:
  html:
    toc: true
    toc-title: "Content"
    toc-location: left
    page-layout: full
---

## Abstract

This interactive lesson engages high school students in exploring data visualization, visual literacy, and accessibility. Students begin with a brief anticipatory activity: given a simple graph (histogram, line graph, scatterplot, etc.), they write a short description of what they observe, swap descriptions with a peer, and attempt to recreate the graph from their peer’s words. This activity highlights the importance of clear communication and accessible design for individuals who are blind or have low vision. After this initial exploration, students are introduced to the principles of alternative text, including demonstrations of screen reader functionality and guidance on writing effective descriptions. Students then revisit the original task, applying what they have learned to improve their graph descriptions. The lesson concludes with a gamified “telephone” activity, where teams pass along graph descriptions and recreate visualizations, followed by a brief reflection on the experience. This activity was implemented as a stand-alone 45-minute lesson in a high school introductory statistics course. Students had prior experience with Exploratory Data Analysis, including descriptive statistics and graphing univariate and bivariate data. Formative assessment occurs through the culminating game, which provides insight into students’ visual literacy and understanding of accessibility principles, while summative assessment integrates these skills into future projects, such as creating accessible visualizations for Machine Learning analyses. Attendees will gain hands-on strategies for incorporating accessible data visualization into their classrooms, practice designing and interpreting graphs with alternative text, and leave with a fully developed 45-minute lesson plan that can be applied in statistics, data science, or mathematics courses. While generative AI tools can now assist with alt text, manual creation remains a valuable exercise to deepen students’ visual literacy and understanding of accessibility. The gamified structure of this activity also fosters engagement, curiosity, and enjoyment in learning.

## Video

Pending video upload on eCOTS website.

## Materials


- [Presentation Slides](https://docs.google.com/presentation/d/15w28lVw2OB1Q4vXV5sBdfJYGZLSJHiMUUeDrFN7-dKc/edit?slide=id.g3e4d0e6df2c_1_76#slide=id.g3e4d0e6df2c_1_76): These slides accompany the video above. 

- [Full Lesson Plan](https://docs.google.com/document/d/1ulyND6GOJg3nnvbmJqTcu6Sf-B9oR_2Bx8nlEm_8XgI/edit?usp=sharing): A detailed lesson plan teachers can use to implement the activity in their courses.

- [Example Graph Cards](https://docs.google.com/document/d/18XQ-WbHB2A1PZjmOFQZ-3tIsDlwBgrRwLRPqHJTNswQ/edit?usp=sharing): Set of cards that were utilized when implementing the activity.

- [Writing Effective Alt-Text Slides](https://docs.google.com/presentation/d/1mSystH6sYyUGWt-6iJ5MUkkxwPaJhfS187ymaZxciVM/edit?usp=sharing): Slides that were used while teaching students.


## References

American Statistical Association & National Council of Teachers of Mathematics. (2020). Pre-K-12 guidelines for assessment and instruction in statistics education II (GAISE II): A framework for statistics and data science education. [https://www.amstat.org/docs/default-source/amstat-documents/gaiseiiprek-12_full.pdf?v=1](https://www.amstat.org/docs/default-source/amstat-documents/gaiseiiprek-12_full.pdf?v=1) 

Doğucu, M., Medina, C., & Castro, A. (2026). Hello data science: A friendly introduction with applications. [https://hellodata.science](https://hellodata.science)